lengths:
  - 16
  - 32
  - 48
  - 80

scalar16:
  ident_bytemask: "0x80"
  ident_val: "0x00"
  length: 16
  instructions:
    -
      opcode_mask: "0xFFFF"
      opcode_eval: "0x0000"
      name: bkpt
    -
      opcode_mask: "0xFFFF"
      opcode_eval: "0x0001"
      name: nop
    -
      opcode_mask: "0xFFFF"
      opcode_eval: "0x0002"
      name: sleep
    -
      opcode_mask: "0xFFFF"
      opcode_eval: "0x0003"
      name: user
    -
      opcode_mask: "0xFFFF"
      opcode_eval: "0x0004"
      name: ei
    -
      opcode_mask: "0xFFFF"
      opcode_eval: "0x0005"
      name: di
    -
      opcode_mask: "0xFFFF"
      opcode_eval: "0x0006"
      name: cbclr
    -
      opcode_mask: "0xFFFF"
      opcode_eval: "0x0007"
      name: cbadd1
    -
      opcode_mask: "0xFFFF"
      opcode_eval: "0x0008"
      name: cbadd2
    -
      opcode_mask: "0xFFFF"
      opcode_eval: "0x0009"
      name: cbadd3
    -
      opcode_mask: "0xFFFF"
      opcode_eval: "0x000A"
      name: rti
    -
      opcode_mask: "0xFFE0"
      opcode_eval: "0x0020"
      name: swi_rd
      arguments:
        -
          name: rd
          type: reg_ref
          bitmask: "0x001F"
    -
      opcode_mask: "0xFFE0"
      opcode_eval: "0x0040"
      name: b_rd
      arguments:
        -
          name: rd
          type: reg_ref
          bitmask: "0x001F"
    -
      opcode_mask: "0xFFE0"
      opcode_eval: "0x0060"
      name: bl_rd
      arguments:
        -
          name: rd
          type: reg_ref
          bitmask: "0x01F"
    -
      opcode_mask: "0xFFF0"
      opcode_eval: "0x0080"
      name: switch.b_rd
      arguments:
        -
          name: rd
          type: reg_ref
          bitmask: "0x000F"
    -
      opcode_mask: "0xFFF0"
      opcode_eval: "0x00A0"
      name: switch_rd
      arguments:
        -
          name: rd
          type: reg_ref
          bitmask: "0x000F"
    -
      opcode_mask: "0xFFE0"
      opcode_eval: "0x00E0"
      name: version
      arguments:
        -
          name: rd
          type: reg_ref
          bitmask: "0x001F"
    -
      opcode_mask: "0xFFC0"
      opcode_eval: "0x01C0"
      name: swi_u
      arguments:
        -
          name: u
          type: immediate
          bitmask: "0x003F"
    -
      opcode_mask: "0xFF80"
      opcode_eval: "0x0200"
      name: ldm_rb-rm_sppl
      arguments:
        -
          name: b
          type: reg_ref_btable
          bitmask: "0x0060"
          rshift: 5
        -
          name: m
          type: reg_ref_mb_indirect
          bitmask: "0x001F"
    -
      opcode_mask: "0xFF80"
      opcode_eval: "0x0280"
      name: stm_rb-rm_spmi
      arguments:
        -
          name: b
          type: reg_ref_btable
          bitmask: "0x0060"
          rshift: 5
        -
          name: m
          type: reg_ref_mb_indirect
          bitmask: "0x001F"       
    -
      opcode_mask: "0xFF80"
      opcode_eval: "0x0300"
      name: ldm_rb-rm_pc_sppl
      arguments:
        -
          name: b
          type: reg_ref_btable
          bitmask: "0x0060"
          rshift: 5
        -
          name: m
          type: reg_ref_mb_indirect
          bitmask: "0x001F"
    -
      opcode_mask: "0xFF80"
      opcode_eval: "0x0380"
      name: stm_rb-rm_lr_spmi
      arguments:
        -
          name: b
          type: reg_ref_btable
          bitmask: "0x0060"
          rshift: 5
        -
          name: m
          type: reg_ref_mb_indirect
          bitmask: "0x001F"
    -
      opcode_mask: "0xFE00"
      opcode_eval: "0x0400"
      name: ld_rd_sprel
      arguments:
        -
          name: o
          type: immediate
          bitmask: "0x01F0"
          rshift: 4
        -
          name: d
          type: reg_ref
          bitmask: "0x000F"
    -
      opcode_mask: "0xFE00"
      opcode_eval: "0x0600"
      name: st_rd_sprel
      arguments:
        -
          name: o
          type: immediate
          bitmask: "0x01F0"
          rshift: 4
        -
          name: d
          type: reg_ref
          bitmask: "0x000F"
    -
      opcode_mask: "0xF900"
      opcode_eval: "0x0800"
      name: ld_ws
      arguments:
        -
          name: w
          type: width_specifier
          bitmask: "0x0600"
          rshift: 9
        -
          name: s
          type: reg_ref_m
          bitmask: "0x00F0"
          rshift: 4
        -
          name: d
          type: reg_ref
          bitmask: "0x000F"
    -
      opcode_mask: "0xF900"
      opcode_eval: "0x0900"
      name: st_ws
      arguments:
        -
          name: w
          type: width_specifier
          bitmask: "0x0600"
          rshift: 9
        -
          name: s
          type: reg_ref_m
          bitmask: "0x00F0"
          rshift: 4
        -
          name: d
          type: reg_ref
          bitmask: "0x000F"
    -
      opcode_mask: "0xF800"
      opcode_eval: "0x1000"
      name: add_rd_sp_o
    -
      opcode_mask: "0xF800"
      opcode_eval: "0x1800"
      name: branch_condition
    -
      opcode_mask: "0xF000"
      opcode_eval: "0x2000"
      name: ld_rd_rs_u_ptr
    -
      opcode_mask: "0xF000"
      opcode_eval: "0x3000"
      name: st_rd_rs_u_ptr
    -
      opcode_mask: "0xF000"
      opcode_eval: "0x4000"
      name: rd_ra_op
    -
      opcode_mask: "0xF000"
      opcode_eval: "0x6000"
      name: rd_u_op

scalar32:
  ident_bytemask: "0x80"
  ident_val: "0x80"
  length: 32
  instructions:
    -
      opcode_mask: "0xF000C000"
      opcode_eval: "0x80000000"
      name: add_cmp_branch_condition
      arguments:
    -
      opcode_mask: "0xF000C000"
      opcode_eval: "0x80004000"
      name:
      arguments:
    -
      opcode_mask: "0xF000C000"
      opcode_eval: "0x80008000"
      name:
      arguments:
    -
      opcode_mask: "0xF000C000"
      opcode_eval: "0x8000C000"
      name:
      arguments:
    -
      opcode_mask: "0xF0800000"
      opcode_eval: "0x90000000"
      name:
      arguments:
    -
      opcode_mask: "0xF0800000"
      opcode_eval: "0x90800000"
      name:
      arguments:
    -
      opcode_mask: "0xFF200060"
      opcode_eval: "0xA0000000"
      name:
      arguments:
    -
      opcode_mask: "0xFF200060"
      opcode_eval: "0xA0200000"
      name:
      arguments:
    -
      opcode_mask: "0xFE200000"
      opcode_eval: "0xA2000000"
      name:
      arguments:
    -
      opcode_mask: "0xFE200000"
      opcode_eval: "0xA2200000"
      name:
      arguments:
    -
      opcode_mask: 
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
    -
      opcode_mask:
      opcode_eval:
      name:
      arguments:
  
scalar48:
  ident_bytemask: "0xF0"
  ident_val: "0xE0"

vector48:
  ident_bytemask: "0xF8"
  ident_val: "0xF0"

vector80:
  ident_bytemask: "0xF8"
  ident_val: "0xF8"
