---
scalar_registers:
  general:
    start: 0
    end: 15
  extended:
    start: 16
    end: 24
    aliases:
      24: gp
  special_purpose:
    start: 25
    end: 31
    aliases:
      25: sp
      26: lr
      28: esp
      29: tp
      30: sr
      31: pc
  processor_control:
    start: 0
    end: 31
    aliases:
      0: PRFPXCS
      1: PRCANARY
      10: PRPOWCTL
      11: PRTIMCTL
      12: PRCORTIM
      13: PRSLPTIM
      14: PROOWCNT
      15: PRORCNT
      16: PRSPINL
    single_bit:
      start: 16
      end: 31
vector_regfile:
  cell_size: 8
  height: 64
  width: 64
  vector_size: 16
  bit_width:
    - 8
    - 16
    - 32
...
